### ISSUE TITLE
error: No such ref 'app/ai.piper.Speech.Provider/x86_64/master' in remote provider-origin when installing Piper provider

### ISSUE THREAD

**Issue by Nardol** [eeejay/spiel-demos#2]
Firstly, I wanted to build the provider myself but I don't want to break system Python packages with pip and doing it using a virtual env does not allow me to use it at all with Orca so I finally take the procedure I did not want, installing using flatpack.
But it is impossible, I have the following error:

```sh
$ flatpak install https://eeejay.github.io/spiel-demos/piper.flatpakref


Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/user/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

error: No such ref 'app/ai.piper.Speech.Provider/x86_64/master' in remote provider-origin
```

I use Debian Bookworm.
The first message is not surprising me, I still have not restarted my session since I installed flatpack.
And because it is related to applications displayed on my desktop, I don't think it is relevant. But the end suggests there is nothing to install.

**Comment by eeejay** [comment]
I think the repo was broken when you tried. Can you try to use the flatpak again?

**Comment by Nardol** [comment]
OK, I've tried again and was able to install successfully?.
Orca still does not use Spiel but I don't think this is related to this repository :wink:
