### ISSUE TITLE
Kind plea I have issue to build for AArch64 Bit architecture

### ISSUE THREAD

**Issue by JanuszChmiel** [eeejay/spiel-demos#3]
Dear elite Rust language developer of this module.
My name is Janusz Chmiel. And I would like to use Espeak speech provider which you have developed with Orca screen reader.
I Am using Orca on my ANdroid 11 phone.
Eventhough it could sound very strange, it really work.
But I Am having issues while building your module.
I Am running openSUSE Tumbleweed for AArch 64 Bit architecture.
Sure, I always do my best to use zypper package manager to install distribution package.
Unfortunately, YOur espeak provider is not compiled inside Opensuse repositories yet.
Or I do not know how to find it.
Only Spiel have been compiled, but no other speech providers.
I have followed The following steps.
   git clone https://github.com/eeejay/spiel-demos.git
   cd spiel-demos/providers/espeak

   # Build and install
   meson setup _build
   meson compile -C _build
   meson install -C _build

But when I have typed The command
   meson compile -C _build
I have got The following severe error.
  The system library `alsa` required by crate `alsa-sys` was not found.
  The file `alsa.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

Please, do you think, that you could tell Me which command to use to find The library location?
And how to construct The pkg path set command so it will point on to needed library?
I would like to rreplace Speech-dispatcher speech server by Spiel and your espeak speech provider for Spiel.
Android kernel do not allow Me to simply use Flatpak.
I want to compare The results while running Spiel instead of Speech-dispatcher.
I want to compare The speech responsiveness and if system will auto close sound channel when Espeak will not speak for 10 Seconds for example.
Speech-dispatcher auto reserve sound channel and channel is not being auto closed.
Sure, because I Am running Pulseaudio for Termux for Android, which uses Opensless protocol to stream audio to other Android audio subsystem so sound can play reliably.

Standard dbus work like A charm on Android, only Dbus-broker do not run by default.

Please could you give Me a helping hand please?

Or do you think, that your project calls some specific Linux kernel system calls which will be 100 % incompatible with The Android kernel?

I can even allow you to use Tmate SSH client and You could connect to my phone remotely so you could try to build your project on my phone remotely.
Sure, it depend on your time, possibilities and on your good will.

Any help will be very welcomed.
Thank xyou for your time and for your support.
With The deepest possible appreciation and with The kindness regards.
Janusz Chmiel

**Comment by JanuszChmiel** [comment]
I AM also suggesting more simple solution for you. COuld you try to compile your package for AArch64 Bit CPU?
You have much more professional knowledge related to building and code compilation.
You could even add it officially to The assets sub folder on your GIThub tree.
What do you think about it please?

**Comment by eeejay** [comment]
I am not familiar with your distro, so I can't give you full support on this. But it seems like you need to install the alsa dev package.

This is early development, perhaps when things stabilize OpenSUSE will package this provider. Without that you will need to figure out how to build and install this yourself, or use a flatpak.

**Comment by JanuszChmiel** [comment]
Dear MR eeejay ,
thank you very much for your advice.
